-- Custom migration: Create legacy SIM-PBB views
-- These views are not managed by Drizzle (no native MySQL view support)

CREATE OR REPLACE VIEW v_nop AS
SELECT
    CONCAT(KD_PROPINSI, KD_DATI2, KD_KECAMATAN, KD_KELURAHAN,
           KD_BLOK, NO_URUT, KD_JNS_OP) AS NOP,
    KD_PROPINSI, KD_DATI2, KD_KECAMATAN, KD_KELURAHAN,
    KD_BLOK, NO_URUT, KD_JNS_OP,
    SUBJEK_PAJAK_ID, JALAN_OP, LUAS_BUMI, JNS_BUMI, NILAI_SISTEM_BUMI
FROM spop;
--> statement-breakpoint
CREATE OR REPLACE VIEW v_tunggakan AS
SELECT
    CONCAT(s.KD_PROPINSI, s.KD_DATI2, s.KD_KECAMATAN, s.KD_KELURAHAN,
           s.KD_BLOK, s.NO_URUT, s.KD_JNS_OP) AS NOP,
    s.THN_PAJAK_SPPT,
    s.PBB_YG_HARUS_DIBAYAR_SPPT,
    COALESCE(SUM(p.JML_SPPT_YG_DIBAYAR), 0) AS SUDAH_DIBAYAR,
    s.PBB_YG_HARUS_DIBAYAR_SPPT - COALESCE(SUM(p.JML_SPPT_YG_DIBAYAR), 0) AS SISA_TUNGGAKAN
FROM sppt s
LEFT JOIN pembayaran_sppt p
    ON  s.KD_PROPINSI = p.KD_PROPINSI
    AND s.KD_DATI2    = p.KD_DATI2
    AND s.KD_KECAMATAN= p.KD_KECAMATAN
    AND s.KD_KELURAHAN= p.KD_KELURAHAN
    AND s.KD_BLOK     = p.KD_BLOK
    AND s.NO_URUT     = p.NO_URUT
    AND s.KD_JNS_OP   = p.KD_JNS_OP
    AND s.THN_PAJAK_SPPT = p.THN_PAJAK_SPPT
    AND p.DIBATALKAN  = 0
WHERE s.STATUS_PEMBATALAN = '0'
  AND s.STATUS_PEMBAYARAN_SPPT <> '1'
GROUP BY s.KD_PROPINSI, s.KD_DATI2, s.KD_KECAMATAN, s.KD_KELURAHAN,
         s.KD_BLOK, s.NO_URUT, s.KD_JNS_OP, s.THN_PAJAK_SPPT;
--> statement-breakpoint
CREATE OR REPLACE VIEW v_realisasi_kelurahan AS
SELECT
    s.KD_PROPINSI,
    s.KD_DATI2,
    s.KD_KECAMATAN,
    s.KD_KELURAHAN,
    s.THN_PAJAK_SPPT,
    COUNT(*)                                        AS JML_OP,
    SUM(s.PBB_YG_HARUS_DIBAYAR_SPPT)               AS TOTAL_KETETAPAN,
    SUM(COALESCE(p.TOTAL_BAYAR, 0))                 AS TOTAL_REALISASI,
    SUM(s.PBB_YG_HARUS_DIBAYAR_SPPT) - SUM(COALESCE(p.TOTAL_BAYAR, 0)) AS SISA
FROM sppt s
LEFT JOIN (
    SELECT KD_PROPINSI, KD_DATI2, KD_KECAMATAN, KD_KELURAHAN,
           KD_BLOK, NO_URUT, KD_JNS_OP, THN_PAJAK_SPPT,
           SUM(JML_SPPT_YG_DIBAYAR) AS TOTAL_BAYAR
    FROM pembayaran_sppt
    WHERE DIBATALKAN = 0
    GROUP BY KD_PROPINSI, KD_DATI2, KD_KECAMATAN, KD_KELURAHAN,
             KD_BLOK, NO_URUT, KD_JNS_OP, THN_PAJAK_SPPT
) p ON s.KD_PROPINSI = p.KD_PROPINSI AND s.KD_DATI2 = p.KD_DATI2
    AND s.KD_KECAMATAN = p.KD_KECAMATAN AND s.KD_KELURAHAN = p.KD_KELURAHAN
    AND s.KD_BLOK = p.KD_BLOK AND s.NO_URUT = p.NO_URUT
    AND s.KD_JNS_OP = p.KD_JNS_OP AND s.THN_PAJAK_SPPT = p.THN_PAJAK_SPPT
WHERE s.STATUS_PEMBATALAN = '0'
GROUP BY s.KD_PROPINSI, s.KD_DATI2, s.KD_KECAMATAN, s.KD_KELURAHAN, s.THN_PAJAK_SPPT;
