import {
  mysqlTable,
  varchar,
  char,
  int,
  tinyint,
  decimal,
  date,
  datetime,
  primaryKey,
  bigint,
  timestamp,
  text,
} from "drizzle-orm/mysql-core";
import { sql } from "drizzle-orm";

// ─── sppt ─────────────────────────────────────────────────
export const sppt = mysqlTable("sppt", {
  kdPropinsi: varchar("KD_PROPINSI", { length: 2 }).notNull(),
  kdDati2: varchar("KD_DATI2", { length: 2 }).notNull(),
  kdKecamatan: varchar("KD_KECAMATAN", { length: 3 }).notNull(),
  kdKelurahan: varchar("KD_KELURAHAN", { length: 3 }).notNull(),
  kdBlok: varchar("KD_BLOK", { length: 3 }).notNull(),
  noUrut: varchar("NO_URUT", { length: 4 }).notNull(),
  kdJnsOp: varchar("KD_JNS_OP", { length: 1 }).notNull(),
  thnPajakSppt: varchar("THN_PAJAK_SPPT", { length: 4 }).notNull(),
  siklusSppt: tinyint("SIKLUS_SPPT"),
  kdKanwilBank: varchar("KD_KANWIL_BANK", { length: 2 }),
  kdKppbbBank: varchar("KD_KPPBB_BANK", { length: 2 }),
  kdBankTunggal: varchar("KD_BANK_TUNGGAL", { length: 2 }),
  kdBankPersepsi: varchar("KD_BANK_PERSEPSI", { length: 2 }),
  kdTp: varchar("KD_TP", { length: 2 }),
  nmWpSppt: varchar("NM_WP_SPPT", { length: 30 }),
  jlnWpSppt: varchar("JLN_WP_SPPT", { length: 30 }),
  blokKavNoWpSppt: varchar("BLOK_KAV_NO_WP_SPPT", { length: 15 }),
  rwWpSppt: varchar("RW_WP_SPPT", { length: 2 }),
  rtWpSppt: varchar("RT_WP_SPPT", { length: 3 }),
  kelurahanWpSppt: varchar("KELURAHAN_WP_SPPT", { length: 30 }),
  kotaWpSppt: varchar("KOTA_WP_SPPT", { length: 30 }),
  kdPosWpSppt: varchar("KD_POS_WP_SPPT", { length: 5 }),
  npwpSppt: varchar("NPWP_SPPT", { length: 15 }),
  noPersilSppt: varchar("NO_PERSIL_SPPT", { length: 5 }),
  kdKlsTanah: varchar("KD_KLS_TANAH", { length: 3 }),
  thnAwalKlsTanah: char("THN_AWAL_KLS_TANAH", { length: 4 }),
  kdKlsBng: varchar("KD_KLS_BNG", { length: 3 }),
  thnAwalKlsBng: char("THN_AWAL_KLS_BNG", { length: 4 }),
  tglJatuhTempoSppt: date("TGL_JATUH_TEMPO_SPPT"),
  luasBumiSppt: bigint("LUAS_BUMI_SPPT", { mode: "number" }).notNull(),
  luasBngSppt: bigint("LUAS_BNG_SPPT", { mode: "number" }).notNull(),
  njopBumiSppt: bigint("NJOP_BUMI_SPPT", { mode: "number" }).notNull(),
  njopBngSppt: bigint("NJOP_BNG_SPPT", { mode: "number" }).notNull(),
  njopSppt: bigint("NJOP_SPPT", { mode: "number" }).notNull(),
  njoptkpSppt: int("NJOPTKP_SPPT").notNull(),
  njkpSppt: bigint("NJKP_SPPT", { mode: "number" }).notNull(),
  pbbTerhutangSppt: bigint("PBB_TERHUTANG_SPPT", { mode: "number" }).notNull(),
  faktorPengurangSppt: bigint("FAKTOR_PENGURANG_SPPT", { mode: "number" }).notNull(),
  pbbYgHarusDibayarSppt: bigint("PBB_YG_HARUS_DIBAYAR_SPPT", { mode: "number" }).notNull(),
  statusPembayaranSppt: tinyint("STATUS_PEMBAYARAN_SPPT"),
  statusTagihanSppt: tinyint("STATUS_TAGIHAN_SPPT"),
  statusCetakSppt: tinyint("STATUS_CETAK_SPPT"),
  statusPembatalan: char("STATUS_PEMBATALAN", { length: 1 }).notNull().default('0'),
  tglTerbitSppt: datetime("TGL_TERBIT_SPPT"),
  tglCetakSppt: datetime("TGL_CETAK_SPPT"),
  nipPencetakSppt: varchar("NIP_PENCETAK_SPPT", { length: 20 }),
}, (table) => [
  primaryKey({ name: "pk_sppt", columns: [table.kdPropinsi, table.kdDati2, table.kdKecamatan, table.kdKelurahan, table.kdBlok, table.noUrut, table.kdJnsOp, table.thnPajakSppt] }),
]);

// ─── sppt_e ─────────────────────────────────────────────────
export const spptE = mysqlTable("sppt_e", {
  kdPropinsi: varchar("KD_PROPINSI", { length: 2 }).notNull(),
  kdDati2: varchar("KD_DATI2", { length: 2 }).notNull(),
  kdKecamatan: varchar("KD_KECAMATAN", { length: 3 }).notNull(),
  kdKelurahan: varchar("KD_KELURAHAN", { length: 3 }).notNull(),
  kdBlok: varchar("KD_BLOK", { length: 3 }).notNull(),
  noUrut: varchar("NO_URUT", { length: 4 }).notNull(),
  kdJnsOp: varchar("KD_JNS_OP", { length: 1 }).notNull(),
  thnPajakSppt: char("THN_PAJAK_SPPT", { length: 4 }).notNull(),
  cetakKe: int("CETAK_KE").notNull(),
  email: varchar("EMAIL", { length: 500 }),
  nmWpSppt: varchar("NM_WP_SPPT", { length: 255 }),
  pbbYgHarusDibayar: bigint("PBB_YG_HARUS_DIBAYAR", { mode: "number" }),
  tglPembayaranTerakhir: date("TGL_PEMBAYARAN_TERAKHIR"),
  tglDibuat: datetime("TGL_DIBUAT"),
  tglEmail: datetime("TGL_EMAIL"),
  tglRecord: timestamp("TGL_RECORD"),
  nipVerifikasi1: varchar("NIP_VERIFIKASI_1", { length: 100 }),
  nipVerifikasi2: varchar("NIP_VERIFIKASI_2", { length: 100 }),
  nipVerifikasi3: varchar("NIP_VERIFIKASI_3", { length: 100 }),
  tglVerifikasi1: datetime("TGL_VERIFIKASI_1"),
  tglVerifikasi2: datetime("TGL_VERIFIKASI_2"),
  tglVerifikasi3: datetime("TGL_VERIFIKASI_3"),
  tglKirimTtd: datetime("TGL_KIRIM_TTD"),
  tglTerimaTtd: datetime("TGL_TERIMA_TTD"),
  fileSppt: text("FILE_SPPT"),
}, (table) => [
  primaryKey({ name: "pk_sppt_e", columns: [table.kdPropinsi, table.kdDati2, table.kdKecamatan, table.kdKelurahan, table.kdBlok, table.noUrut, table.kdJnsOp, table.thnPajakSppt, table.cetakKe] }),
]);

// ─── sppt_op_bersama ─────────────────────────────────────────────────
export const spptOpBersama = mysqlTable("sppt_op_bersama", {
  kdPropinsi: varchar("KD_PROPINSI", { length: 2 }).notNull(),
  kdDati2: varchar("KD_DATI2", { length: 2 }).notNull(),
  kdKecamatan: varchar("KD_KECAMATAN", { length: 3 }).notNull(),
  kdKelurahan: varchar("KD_KELURAHAN", { length: 3 }).notNull(),
  kdBlok: varchar("KD_BLOK", { length: 3 }).notNull(),
  noUrut: varchar("NO_URUT", { length: 4 }).notNull(),
  kdJnsOp: varchar("KD_JNS_OP", { length: 1 }).notNull(),
  thnPajakSppt: varchar("THN_PAJAK_SPPT", { length: 4 }).notNull(),
  kdKlsTanah: varchar("KD_KLS_TANAH", { length: 3 }).notNull(),
  thnAwalKlsTanah: varchar("THN_AWAL_KLS_TANAH", { length: 4 }).notNull(),
  kdKlsBng: varchar("KD_KLS_BNG", { length: 3 }).notNull(),
  thnAwalKlsBng: varchar("THN_AWAL_KLS_BNG", { length: 4 }).notNull(),
  luasBumiBebanSppt: bigint("LUAS_BUMI_BEBAN_SPPT", { mode: "number" }).notNull(),
  luasBngBebanSppt: bigint("LUAS_BNG_BEBAN_SPPT", { mode: "number" }).notNull(),
  njopBumiBebanSppt: bigint("NJOP_BUMI_BEBAN_SPPT", { mode: "number" }).notNull(),
  njopBngBebanSppt: bigint("NJOP_BNG_BEBAN_SPPT", { mode: "number" }).notNull(),
}, (table) => [
  primaryKey({ name: "pk_sppt_op_bersama", columns: [table.kdPropinsi, table.kdDati2, table.kdKecamatan, table.kdKelurahan, table.kdBlok, table.noUrut, table.kdJnsOp, table.thnPajakSppt] }),
]);

// ─── histori_sppt ─────────────────────────────────────────────────
// History table for SPPT recalculation (BR-08)
export const historiSppt = mysqlTable("histori_sppt", {
  kdPropinsi: varchar("KD_PROPINSI", { length: 2 }).notNull(),
  kdDati2: varchar("KD_DATI2", { length: 2 }).notNull(),
  kdKecamatan: varchar("KD_KECAMATAN", { length: 3 }).notNull(),
  kdKelurahan: varchar("KD_KELURAHAN", { length: 3 }).notNull(),
  kdBlok: varchar("KD_BLOK", { length: 3 }).notNull(),
  noUrut: varchar("NO_URUT", { length: 4 }).notNull(),
  kdJnsOp: varchar("KD_JNS_OP", { length: 1 }).notNull(),
  thnPajakSppt: int("THN_PAJAK_SPPT").notNull(),
  siklusSppt: int("SIKLUS_SPPT").notNull(),
  kdKanwilBank: varchar("KD_KANWIL_BANK", { length: 2 }),
  kdKppbbBank: varchar("KD_KPPBB_BANK", { length: 2 }),
  kdBankTunggal: varchar("KD_BANK_TUNGGAL", { length: 2 }),
  kdBankPersepsi: varchar("KD_BANK_PERSEPSI", { length: 2 }),
  kdTp: varchar("KD_TP", { length: 2 }),
  nmWpSppt: varchar("NM_WP_SPPT", { length: 30 }),
  jlnWpSppt: varchar("JLN_WP_SPPT", { length: 30 }),
  blokKavNoWpSppt: varchar("BLOK_KAV_NO_WP_SPPT", { length: 15 }),
  rwWpSppt: varchar("RW_WP_SPPT", { length: 2 }),
  rtWpSppt: varchar("RT_WP_SPPT", { length: 3 }),
  kelurahanWpSppt: varchar("KELURAHAN_WP_SPPT", { length: 30 }),
  kotaWpSppt: varchar("KOTA_WP_SPPT", { length: 30 }),
  kdPosWpSppt: varchar("KD_POS_WP_SPPT", { length: 5 }),
  npwpSppt: varchar("NPWP_SPPT", { length: 15 }),
  noPersilSppt: varchar("NO_PERSIL_SPPT", { length: 5 }),
  kdKlsTanah: varchar("KD_KLS_TANAH", { length: 3 }),
  thnAwalKlsTanah: int("THN_AWAL_KLS_TANAH"),
  kdKlsBng: varchar("KD_KLS_BNG", { length: 3 }),
  thnAwalKlsBng: int("THN_AWAL_KLS_BNG"),
  tglJatuhTempoSppt: date("TGL_JATUH_TEMPO_SPPT"),
  luasBumiSppt: bigint("LUAS_BUMI_SPPT", { mode: "number" }),
  luasBngSppt: bigint("LUAS_BNG_SPPT", { mode: "number" }),
  njopBumiSppt: bigint("NJOP_BUMI_SPPT", { mode: "number" }),
  njopBngSppt: bigint("NJOP_BNG_SPPT", { mode: "number" }),
  njopSppt: bigint("NJOP_SPPT", { mode: "number" }),
  njoptkpSppt: int("NJOPTKP_SPPT"),
  njkpSppt: bigint("NJKP_SPPT", { mode: "number" }),
  pbbTerhutangSppt: bigint("PBB_TERHUTANG_SPPT", { mode: "number" }),
  faktorPengurangSppt: bigint("FAKTOR_PENGURANG_SPPT", { mode: "number" }),
  pbbYgHarusDibayarSppt: bigint("PBB_YG_HARUS_DIBAYAR_SPPT", { mode: "number" }),
  statusPembayaranSppt: int("STATUS_PEMBAYARAN_SPPT"),
  statusTagihanSppt: int("STATUS_TAGIHAN_SPPT"),
  statusCetakSppt: int("STATUS_CETAK_SPPT"),
  tglTerbitSppt: datetime("TGL_TERBIT_SPPT"),
  tglCetakSppt: datetime("TGL_CETAK_SPPT"),
  nipPencetakSppt: varchar("NIP_PENCETAK_SPPT", { length: 20 }),
  namaPencetakSppt: varchar("NAMA_PENCETAK_SPPT", { length: 100 }),
  // Additional fields for recalculation tracking
  nipPetugas: varchar("NIP_PETUGAS", { length: 50 }),
  keterangan: text("KETERANGAN"),
  tglPerubahan: datetime("TGL_PERUBAHAN").default(sql`CURRENT_TIMESTAMP`),
}, (table) => [
  primaryKey({ name: "pk_histori_sppt", columns: [table.kdPropinsi, table.kdDati2, table.kdKecamatan, table.kdKelurahan, table.kdBlok, table.noUrut, table.kdJnsOp, table.thnPajakSppt, table.siklusSppt] }),
]);
